/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "funcionesBanco.h"

int *actualizardepositar_1_svc(depositar *argp, struct svc_req *rqstp)
{
	static int  result;
	result = argp->saldo + argp->monto;
	return &result;
}

int *actualizarretirar_1_svc(retirar *argp, struct svc_req *rqstp)
{
	static int  result;
	result = argp->saldo - argp->monto;
	return &result;
}
