/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "funcionesBanco.h"


void
servidor_bancario_1(char *host)
{
	int saldo = 500;
	int opcion;
	CLIENT *clnt;
	int  *result_1;
	depositar  actualizardepositar_1_arg;
	int  *result_2;
	retirar  actualizarretirar_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SERVIDOR_BANCARIO, VERSION_ACTUALIZAR, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("\t\t\tBANCO DE LOJA \n");
	printf("Su cuenta actualmente tiene %d\n", saldo);
	printf("Escoja una opcion: \n");
	printf("1. Depositar\n");
	printf("2. Retirar\n");
	printf("3. Seleccione cualquier botón para salir\n");
	scanf("%d", &opcion);
	if (opcion==1){
		printf("Ingrese el monto a depositar: \n");
		scanf("%d", &actualizardepositar_1_arg.monto);
		actualizardepositar_1_arg.saldo = saldo;
		result_1 = actualizardepositar_1(&actualizardepositar_1_arg, clnt);
		printf("Su deposito a sido realizado con exito\n");
		if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
		}
		saldo = *result_1;
		printf("Su cuenta actualmente tiene %d \n", saldo);
		printf("\n");
	}else if (opcion==2){	
		printf("Ingrese el monto a retirar: \n");
		scanf("%d", &actualizarretirar_1_arg.monto);
		if (actualizarretirar_1_arg.monto > saldo)
		{
			printf("No puede realizar esta accion por falta de fondos");
			actualizarretirar_1_arg.monto = 0;
		}else{
			actualizarretirar_1_arg.saldo = saldo;	
			result_2 = actualizarretirar_1(&actualizarretirar_1_arg, clnt);
			printf("Su retiro a sido realizado con exito\n");
			if (result_2 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		saldo = *result_2;
		printf("Su cuenta actualmente tiene %d \n", saldo);
		printf("\n");
		}
	}else{
		printf("Gracias por usar nuestros servicios \n");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	servidor_bancario_1 (host);
exit (0);
}
