/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "funcionesBanco.h"

bool_t
xdr_depositar (XDR *xdrs, depositar *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->opcion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->monto))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->saldo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_retirar (XDR *xdrs, retirar *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->opcion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->monto))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->saldo))
		 return FALSE;
	return TRUE;
}
